version: "2.9.7"

services:
  app:
    build: .
    ports:
        - "8080:8080"
    networks:
      - s-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    networks:
      - s-network

networks:
  s-network:
    driver: bridge